# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 06:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserName',
        ),
    ]
